// <auto-generated />
namespace Procurment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SupplierName_added_to_Payments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SupplierName_added_to_Payments));
        
        string IMigrationMetadata.Id
        {
            get { return "201810040548516_SupplierName_added_to_Payments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
